import {
  signInUser,
  signOutUser,
  toggleLoading,
} from "store/auth-slice/auth.slice";
import {
  setUserId,
  addNote,
  getNotes,
  addLabel,
  getLabels,
  updateLabel,
  deleteLabel,
  deleteNote,
  updateNote,
  updateNoteColor,
  addLabelChips,
  removeLabelChip,
  emptyLabelChips,
  deleteLabelsFromNote,
  deleteNoteFromLabels,
  getDeletedNotes,
  deleteAllNotes,
  deleteNoteForever,
  restoreNote,
} from "store/notes-slice/notes.slice";
import {
  showInputBar,
  hideInputBar,
  toggleDrawer,
  toggleMode,
  toggleView,
  showSnackBar,
  hideSnackBar,
  showLabelDialog,
  hideLabelDialog,
  showNoteDialog,
  hideNoteDialog,
  showDeleteDialog,
  hideDeleteDialog,
} from "store/toggle-slice/toggles.slice";

export {
  signInUser,
  signOutUser,
  toggleLoading,
  setUserId,
  addNote,
  getNotes,
  getLabels,
  updateLabel,
  deleteLabel,
  deleteNote,
  addLabel,
  updateNoteColor,
  updateNote,
  showInputBar,
  hideInputBar,
  toggleDrawer,
  toggleMode,
  toggleView,
  showSnackBar,
  hideSnackBar,
  showLabelDialog,
  hideLabelDialog,
  showNoteDialog,
  hideNoteDialog,
  showDeleteDialog,
  hideDeleteDialog,
  addLabelChips,
  removeLabelChip,
  emptyLabelChips,
  deleteLabelsFromNote,
  deleteNoteFromLabels,
  getDeletedNotes,
  deleteAllNotes,
  deleteNoteForever,
  restoreNote,
};
